In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd


Bad key "text.kerning_factor" on line 4 in
/home/minhmap/anaconda3/envs/minh_env/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution


In [2]:
data = pd.read_csv("./iris_1D.csv")
data

Petal_Length  Label
0           1.4    0.0
1           1.0    0.0
2           1.5    0.0
3           3.1    1.0
4           3.8    1.0
5           4.1    1.0

In [3]:
# data["Petal_Length"].to_numpy().shape
# print(data["Petal_Length"].to_numpy())

In [4]:
# get x
x_data = data["Petal_Length"].to_numpy()
x_data = x_data.reshape(6, 1) # change (6, ) --> (6, 1)
print(x_data)

[[1.4]
 [1. ]
 [1.5]
 [3.1]
 [3.8]
 [4.1]]


In [5]:
# get y
y_data = data["Label"].to_numpy()
print(y_data)

[0. 0. 0. 1. 1. 1.]


In [6]:
# unknown input
x_test = [[2.4]]

# Cách 1:

In [7]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=3)

In [8]:
y_pred = classifier.predict(x_test)
print(y_pred)

[0.]


# Cách 2:

In [9]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=6)

#### Sử dụng phương thức .kneighbors(x_test) để trả về khoảng cách và chỉ số của các hàng xóm gần nhất.

In [10]:
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[0.7, 0.9, 1. , 1.4, 1.4, 1.7]]), array([[3, 2, 0, 1, 4, 5]]))


In [11]:
classifier.classes_[classifier._y[3]]

1.0

In [12]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier

# Tạo dữ liệu giả lập
X, y = make_classification(n_samples=100, n_features=2, n_informative=2, n_redundant=0, random_state=42)

# Dữ liệu test
x_test = np.array([[1, 1], [0, 0]])

# Cách tiếp cận 1 (C1)
print("Cách tiếp cận 1 (C1):")
classifier_c1 = KNeighborsClassifier(n_neighbors=3)
classifier_c1.fit(X, y)
y_pred_c1 = classifier_c1.predict(x_test)
print("Dự đoán (C1):", y_pred_c1)
print()

# Cách tiếp cận 2 (C2)
print("Cách tiếp cận 2 (C2):")
classifier_c2 = KNeighborsClassifier(n_neighbors=3)
classifier_c2.fit(X, y)
distances, indices = classifier_c2.kneighbors(x_test)
for i, (dist, ind) in enumerate(zip(distances, indices)):
    print(f"Điểm test {i+1}:")
    print("Khoảng cách đến hàng xóm gần nhất:", dist)
    print("Chỉ số hàng xóm gần nhất:", ind)
    predicted_label = classifier_c2.classes_[classifier_c2._y[ind]]
    print("Nhãn dự đoán:", predicted_label)
    print()

Cách tiếp cận 1 (C1):
Dự đoán (C1): [1 1]

Cách tiếp cận 2 (C2):
Điểm test 1:
Khoảng cách đến hàng xóm gần nhất: [0.20089848 0.27154335 0.31542388]
Chỉ số hàng xóm gần nhất: [52 53 69]
Nhãn dự đoán: [1 1 1]

Điểm test 2:
Khoảng cách đến hàng xóm gần nhất: [0.1140306  0.19039667 0.28694263]
Chỉ số hàng xóm gần nhất: [25 21 29]
Nhãn dự đoán: [0 1 1]

