In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn import neighbors, datasets
import pandas as pd


Bad key "text.kerning_factor" on line 4 in
/home/minhmap/anaconda3/envs/minh_env/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution


In [16]:
data = pd.read_csv('iris_2D.csv')
data

Petal_Length  Petal_Width  Label
0           1.4          0.2    0.0
1           1.3          0.4    0.0
2           1.4          0.3    0.0
3           4.0          1.0    1.0
4           4.7          1.4    1.0
5           3.6          1.3    1.0

#### Get value x

#### 
Khi làm việc với thư viện pandas, dữ liệu trong các cột của DataFrame được lưu trữ dưới dạng các đối tượng Series. Để thực hiện các phép toán hoặc truyền dữ liệu vào các mô hình học máy khác, thường bạn cần chuyển đổi dữ liệu từ dạng Series thành dạng NumPy array. 

Khi làm việc với thư viện pandas, dữ liệu trong các cột của DataFrame được lưu trữ dưới dạng các đối tượng Series. Để thực hiện các phép toán hoặc truyền dữ liệu vào các mô hình học máy khác, thường bạn cần chuyển đổi dữ liệu từ dạng Series thành dạng NumPy array.

Trong đoạn mã bạn đã đề cập:

python
Copy code
x_data = data["Petal_Length", "Petal_Width"].to_numpy()
x_data = x_data.reshape(6, 2)
data["Petal_Length", "Petal_Width"].to_numpy(): Đoạn mã này lấy ra các cột "Petal_Length" và "Petal_Width" từ DataFrame data và chuyển chúng thành một mảng NumPy bằng cách sử dụng phương thức to_numpy(). Việc chuyển đổi này cần thiết để bạn có thể làm việc với dữ liệu trong mô hình học máy hoặc các phép toán khác.

x_data.reshape(6, 2): Dòng này thực hiện việc reshape lại dữ liệu thành một ma trận có kích thước (6, 2). Điều này giả định rằng bạn đã lấy 6 mẫu từ các cột "Petal_Length" và "Petal_Width". Quá trình reshape này có thể cần thiết tùy theo cách bạn muốn sử dụng dữ liệu trong mô hình của mình.

Tóm lại, việc chuyển đổi dữ liệu thành mảng NumPy thông qua to_numpy() giúp bạn dễ dàng làm việc với dữ liệu trong các thư viện học máy và khoa học dữ liệu khác, cũng như thực hiện các phép toán và xử lý dữ liệu một cách hiệu quả hơn.

In [4]:
# get x
x_data = data[["Petal_Length", "Petal_Width"]].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]


In [17]:
# get y
y_data = data["Label"].to_numpy()
print(y_data)

[0. 0. 0. 1. 1. 1.]


In [10]:
# unknown input
x_test = [[2.6, 0.7]]

#### Way 1

In [18]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=1)

In [21]:
y_pred = classifier.predict(x_test)
print(pred)

[1.]


#### Way 2

In [41]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=6)

In [42]:
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[1.16619038, 1.26491106, 1.3       , 1.33416641, 1.43178211,
        2.21359436]]), array([[5, 2, 0, 1, 3, 4]]))


In [47]:
classifier.classes_[classifier._y[3]]

1.0